name: Add Maintainer

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  org-label:
    name: Org Labeling
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        if: github.event.action == 'opened'
        uses: JamesSingleton/is-organization-member@1.0.0
        with:
          organization: hashicorp
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Label Maintainer 
        run: |
          echo ${{ steps.is_organization_member.outputs.result }}
        
      - name: Label Maintainer 
        if: |
          steps.is_organization_member.outputs.result == false
        uses: andymckay/labeler@master
        with:
          add-labels: "Maintainer"

